name: deploy hugo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
      - name: create theme
        run: mkdir /themes
      - name: create aws
        run: mkdir /themes/aws-community-day-baltic-theme/
      - name: import
        uses:  actions/checkout@v3
        with:
          repository: 'aws3city/aws-community-day-baltic-theme'
          path: themes/aws-community-day-baltic-theme
     
      - name: Build
        env:
          TZ: 'Europe/Berlin'
        run: hugo --minify
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3