name: deploy hugo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
      - name: Build
        env:
          TZ: 'Europe/Berlin'
        run: hugo --minify
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3