name: deploy hugo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.1'
          extended: true
      - name: create theme
        run: mkdir ./themes
      - name: create aws
        run: mkdir ./themes/aws-community-day/
      - name: import
        uses:  actions/checkout@v3
        with:
          repository: 'aws3city/aws-community-day-baltic-theme'
          path: './themes/aws-community-day/'   
      - name: check
        run: ls themes/aws-community-day/
      - name: Build
        run: hugo
      - name: check
        run: ls
      - name: checkout
        uses: actions/checkout@master
      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}         
          AWS_S3_ENDPOINT: 'https://awsbaltic.eu/'
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: './public'