name: deploy hugo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
      - name: Build
        env:
          TZ: 'Europe/Berlin'
        run: hugo --minify
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3